### ISSUE TITLE
[theme-blog] Unable to build with `v2.0.0-beta.10`

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#597]
### Problem

Today I updated my blog to `beta.10` and got the following error. With `beta.9`, It is working fine.

```
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/mario/Code/vikasraj.dev/node_modules/.pnpm/nextra-theme-blog@2.0.0-beta.10_53oqlnqnxhbetdy4ljlkkvmoby/node_modules/next/head' imported from /home/mario/Code/vikasraj.dev/node_modules/.pnpm/nextra-theme-blog@2.0.0-beta.10_53oqlnqnxhbetdy4ljlkkvmoby/node_modules/nextra-theme-blog/dist/index.mjs
Did you mean to import next@12.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/head.js?
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

### Packages

```json
"next": "^12.2.3",
"nextra": "2.0.0-beta.10",
"nextra-theme-blog": "2.0.0-beta.10",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

**Comment by PabloLION** [comment]
I tested with `v2.0.0-beta.10` and `nextra-theme-docs` in my test repo [PabloLION/zzz-test-nextra-356-src-test](https://github.com/PabloLION/zzz-test-nextra-356-src-test) and it worked fine.

**Comment by PabloLION** [comment]
With this commit. https://github.com/PabloLION/zzz-test-nextra-356-src-test/commit/0972fe3baa419ba528237f4c845a56fb89e32511

**Comment by PabloLION** [comment]
I also tested the `nextra-theme-blog@2.0.0-beta.10` here https://github.com/PabloLION/zzz-test-nextra-356-src-test/commit/515bb2bd2fc12e4517f222abf2af4fb3b4e3ee8a .

Same error was thrown. Seems that the `next/head` was missing?

**Comment by SincerelyFaust** [comment]
I've attempted building the blog with `beta.12` and this is what I get:
```
./node_modules/.pnpm/nextra-theme-blog@2.0.0-beta.12_53oqlnqnxhbetdy4ljlkkvmoby/node_modules/nextra-theme-blog/dist/index.js:271:0
Module not found: Can't resolve 'react-cusdis'

Import trace for requested module:
./pages/index.mdx

https://nextjs.org/docs/messages/module-not-found```

**Comment by numToStr** [comment]
I think this is regression introduced in #602. @promer94

**Comment by promer94** [comment]
i will fix this later 👌
