### ISSUE TITLE
TypeError: page.generateMetadata is not a function when using withSentryConfig in Nextra project

### ISSUE THREAD

**Issue by Q0** [shuding/nextra#4367]
If next.config.mjs uses `withSentryConfig`, the project stops working and writes an error

```
 ⨯ [TypeError: page.generateMetadata is not a function] {
  type: 'TypeError',
  page: '/docs'
}
```

Instructions how to repeat the error:

Windows/Linux

repo: https://github.com/Glitch-Seekers/Nextra4-Sentry-Bug

1. `git pull git@github.com:Glitch-Seekers/Nextra4-Sentry-Bug.git`
2. `yarn install`
3. `yarn dev`

In the "ok" branch of https://github.com/Glitch-Seekers/Nextra4-Sentry-Bug/tree/ok I removed `withSentryConfig` and the project worked.

Any idea what the problem might be and how to fix it?

versions:

```
        "@sentry/nextjs": "^9.6.1",
        "@tailwindcss/postcss": "^4.0.14",
        "next": "^15.2.3",
        "nextra": "^4.2.16",
        "nextra-theme-docs": "^4.2.16",
        "postcss": "^8.5.3",
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
        "tailwindcss": "^4.0.14"
```

**Comment by ftzi** [comment]
Same issue here

**Comment by ftzi** [comment]
Huge thanks, @dimaMachina! 🤗

Taking advantage of this, could you check if the nextra docs is working with the new next 15.3.0? When I downgrade back to 15.2.4 it works again. Maybe it's just a local issue here with my configs so I don't know if it's worth creating an issue.

**Comment by dimaMachina** [comment]
adjusted support in https://github.com/shuding/nextra/releases/tag/nextra%404.3.0-alpha.13
